name: apparence_cli
description: A sample command-line application.
version: 3.0.4
# homepage: https://www.example.com
environment:
  sdk: ">=3.1.0 <4.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
dependencies:
  args: ^2.4.2
  http: ^1.1.0
  mason: ^0.1.0-dev.52
  path: ^1.8.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
