workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - stacks-keystore
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: {{android_package}} # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "alpha" # <-- Put your track here (alpha, beta, production, internal)
      flutter: stable
    triggering:
      cancel_previous_builds: true
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: false
          source: false
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Unit tests
        script: | 
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --dart-define=ENV=prod \
            --dart-define=BACKEND_URL=$BACKEND_URL \
            --dart-define=SENTRY_DSN=$SENTRY_DSN \
            --dart-define=GLASSFY_TOKEN=$GLASSFY_TOKEN \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - {{email_notification_adress}} # <-- Put your email here or add others recipients
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
          - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.apparence.myapp # <-- Put your bundle identifier here
      vars:
        APP_ID: {{apple_store_app_id}} # <-- Put your APP ID here (you can find it in the URL of your app in App Store Connect)
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    triggering:
      cancel_previous_builds: true
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: false
          source: false
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze # <-- remove if you don't like flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: false  # You should never build an app that has failing tests.
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --dart-define=ENV=prod \
            --dart-define=BACKEND_URL=$BACKEND_URL \
            --dart-define=SENTRY_DSN=$SENTRY_DSN \
            --dart-define=GLASSFY_TOKEN=$GLASSFY_TOKEN \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - {{email_notification_adress}} # <-- Put your email here or add others recipients
        notify:
          success: true 
          failure: true 
      app_store_connect:
        # Use codemagic integreation (easier)
        auth: integration
        # ====================================
        ## Or push all keys manually here
        ## ====================================  
        #api_key: $APP_STORE_CONNECT_PRIVATE_KEY 
        #key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        #issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        ## ====================================  
        submit_to_app_store: true # Optional, defaults to MANUAL. Supported values: MANUAL, AFTER_APPROVAL or SCHEDULED
        release_type: MANUAL  
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - apparence # <-- Put your beta group name here
        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        #copyright: 2023 Apparence.io